image: docker:latest

include:
  - '/.gitlab-ci/docker-service.yml'
  - '/.gitlab-ci/before-script.yml'

stages:
  - reset

reset:
  stage: reset
  needs: []
  variables:
    TS_MANAGEMENT_ACTION: Password - Reset
  script:
    - cd terrashell/src && go run ./main.go && cd ../..
  artifacts:
    paths:
      - ./password.csv
    expire_in: 1 day
  when: manual
