image: docker:latest

include:
  - '/.gitlab-ci/docker-service.yml'
  - '/.gitlab-ci/before-script.yml'

stages:
  - create
  - add-key
  - remove-key
  - delete

create:
  stage: create
  needs: []
  variables:
    TS_MANAGEMENT_ACTION: Secret - Create
  script:
    - cd terrashell/src && go run ./main.go && cd ../..
  artifacts:
    paths:
      - ./secret.csv
    expire_in: 1 day
  when: manual

add-key:
  stage: add-key
  needs: []
  variables:
    TS_MANAGEMENT_ACTION: Secret - Add Key
  script:
    - cd terrashell/src && go run ./main.go && cd ../..
  artifacts:
    paths:
      - ./secret.csv
    expire_in: 1 day
  when: manual

remove-key:
  stage: remove-key
  needs: []
  variables:
    TS_MANAGEMENT_ACTION: Secret - Remove Key
  script:
    - cd terrashell/src && go run ./main.go && cd ../..
  artifacts:
    paths:
      - ./secret.csv
    expire_in: 1 day
  when: manual

delete:
  stage: delete
  needs: []
  variables:
    TS_MANAGEMENT_ACTION: Secret - Delete
  script:
    - cd terrashell/src && go run ./main.go && cd ../..
  artifacts:
    paths:
      - ./secret.csv
    expire_in: 1 day
  when: manual
